APP_NAME = "amcrest2mqtt"
MANUFACTURER = "Amcrest"

CAMERA_EVENTS_SPECIFIER = "All"
CAMERA_EVENTS_RETRIES = 5
CAMERA_EVENTS_TIMEOUT = (10.00, 3600)  # (connect timeout, read timeout)

COMPONENT_BINARY_SENSOR = "binary_sensor"
COMPONENT_LIGHT = "light"
COMPONENT_NUMBER = "number"
COMPONENT_SENSOR = "sensor"
COMPONENT_SWITCH = "switch"

CONFIG_SIREN_VOLUME = "VideoTalkPhoneGeneral.RingVolume"
CONFIG_LIGHT_MODE = "Lighting_V2[0][0][1].Mode"
CONFIG_LIGHT_STATE = "Lighting_V2[0][0][1].State"
CONFIG_WATERMARK = "VideoWidget[0].PictureTitle.EncodeBlend"
CONFIG_INDICATOR_LIGHT = "LightGlobal[0].Enable"

DEFAULT_AMCREST_PORT = 80
DEFAULT_AMCREST_USERNAME = "admin"
DEFAULT_DOORBELL_OFF_TIMEOUT = 10.0
DEFAULT_STORAGE_POLL_INTERVAL = 3600
DEFAULT_CONFIG_POLL_INTERVAL = 60
DEFAULT_MQTT_HOST = "localhost"
DEFAULT_MQTT_QOS = 0
DEFAULT_MQTT_PORT = 1883
DEFAULT_HOME_ASSISTANT_PREFIX = "homeassistant"

DEVICE_CLASS_MOTION = "motion"

DEVICE_TYPE_AD110 = "AD110"
DEVICE_TYPE_AD410 = "AD410"

ENTITY_CATEGORY_CONFIG = "config"
ENTITY_CATEGORY_DIAGNOSTIC = "diagnostic"

ICON_FACE_RECOGNITION = "mdi:face-recognition"
ICON_FLASHLIGHT = "mdi:flashlight"
ICON_MICRO_SD = "mdi:micro-sd"
ICON_VOLUME_HIGH = "mdi:volume-high"
ICON_WATERMARK = "mdi:watermark"
ICON_RADIOBOX_MARKED = "mdi:radiobox-marked"
ICON_CIRCLE_OUTLINE = "mdi:circle-outline"

LIGHT_EFFECT_NONE = "None"
LIGHT_EFFECT_STROBE = "Strobe (30sec)"

MISSING = object()  # Sentinel

PAYLOAD_ON = "on"
PAYLOAD_OFF = "off"
PAYLOAD_ONLINE = "online"
PAYLOAD_OFFLINE = "offline"

TIME_CAMERA_PING_INTERVAL = 30  # Seconds
TIME_CAMERA_PING_TIMEOUT = 100  # Seconds

UNITS_PERCENTAGE = "%"
UNITS_GIGABYTES = "GB"
